version: '3.5'

networks:
  gyarados:
    external: true

services:
  airquality-react:
    image: juoksijapoika/airquality-react:latest
    container_name: airquality-react
    volumes:
      - /opt/configuration/airquality-react:/app/environment
    restart: always
    networks:
      - gyarados
    ports:
      - 8081:8080