version: '3.5'

networks:
  gyarados:
    external: true

services:
  airquality-react:
    image: juoksijapoika/airquality-react:latest
    container_name: airquality-react
    restart: always
    networks:
      - gyarados
    ports:
      - "127.0.0.1:8081:8081"